// Snippets
export const GET_SNIPPETS = 'GET_SNIPPETS';
export const GET_SNIPPETS_SUCCESS = 'GET_SNIPPETS_SUCCESS';
export const GET_SNIPPETS_FAILURE = 'GET_SNIPPETS_FAILURE'; 

export const ADD_SNIPPET = 'ADD_SNIPPET'
export const ADD_SNIPPET_SUCCESS = 'ADD_SNIPPET_SUCCESS'
export const ADD_SNIPPET_FAILURE = 'ADD_SNIPPET_FAILURE'